upf4ros2_navigation_action:
  ros__parameters:
    wps:
      - "entrance"
      - "5.80"
      - "-4.63"
      - "-0.77"
      - "0.63"

      - "kitchen"
      - "7.22"
      - "-0.97"
      - "0.002"
      - "1.0"

      - "livingroom"
      - "1.57"
      - "0.70"
      - "-0.001"
      - "1.0"

      - "bedroom"
      - "-6.28"
      - "-0.14"
      - "-0.001"
      - "1.0"

      - "room"
      - "-7.78"
      - "-2.76"
      - "-0.001"
      - "1.0"

      - "gym"
      - "1.85"
      - "4.38"
      - "-0.005"
      - "1.0"