(define (domain social-care-tamer-complex-integrated)
  (:requirements :typing :durative-actions :numeric-fluents :negative-preconditions)

  (:types location robot person item request resource capability - object)

  (:constants
    nav-cap delivery-cap social-cap monitor-cap lift-left-cap lift-right-cap admin-cap guide-cap - capability)

  (:predicates
    (connected ?from - location ?to - location)
    (corridor-link ?from - location ?to - location)
    (blocked ?from - location ?to - location)
    (can-enter ?r - robot ?l - location)
    (can-move ?r - robot ?from - location ?to - location)
    (robot-at ?r - robot ?l - location)
    (person-at ?p - person ?l - location)
    (item-at ?i - item ?l - location)
    (robot-free ?r - robot)
    (available ?x - resource)
    (charger-for ?dock - resource ?l - location)
    (uses-corridor ?from - location ?to - location ?c - resource)
    (uses-terminal ?q - request ?terminal - resource)
    (robot-has ?r - robot ?c - capability)
    (can-pick ?r - robot ?i - item)
    (can-deliver ?r - robot ?q - request)
    (can-guide ?r - robot ?q - request)
    (can-comfort ?r - robot ?q - request)
    (can-assist ?monitor - robot ?actor - robot ?q - request)
    (can-handover ?from - robot ?to - robot ?i - item ?l - location)
    (can-cooperate ?left - robot ?right - robot ?i - item)
    (request-person ?q - request ?p - person)
    (request-item ?q - request ?i - item)
    (request-origin ?q - request ?l - location)
    (request-destination ?q - request ?l - location)
    (request-capability ?q - request ?c - capability)
    (carrying ?r - robot ?i - item)
    (co-carrying ?left - robot ?right - robot ?i - item)
    (handover-done ?i - item ?from - robot ?to - robot)
    (delivered ?i - item ?p - person)
    (comforted ?p - person)
    (assisted ?p - person)
    (checked-in ?p - person)
    (guided ?p - person ?l - location)
    (service-completed ?q - request))

  (:functions
    (battery ?r - robot)
    (battery-max ?r - robot)
    (speed ?r - robot)
    (energy-rate ?r - robot)
    (payload-capacity ?r - robot)
    (current-load ?r - robot)
    (item-weight ?i - item)
    (item-size ?i - item)
    (request-priority ?q - request)
    (task-duration ?q - request)
    (total-cost))

  (:durative-action navigate
    :parameters (?r - robot ?from - location ?to - location)
    :duration (= ?duration (+ 2 (/ 3 (speed ?r))))
    :condition (and
      (at start (robot-at ?r ?from))
      (at start (connected ?from ?to))
      (at start (can-move ?r ?from ?to))
      (at start (not (blocked ?from ?to)))
      (at start (can-enter ?r ?to))
      (at start (robot-free ?r))
      (at start (robot-has ?r nav-cap))
      (at start (>= (battery ?r) (* 3 (energy-rate ?r))))
      (over all (not (blocked ?from ?to))))
    :effect (and
      (at start (not (robot-free ?r)))
      (at start (not (robot-at ?r ?from)))
      (at start (decrease (battery ?r) (* 3 (energy-rate ?r))))
      (at end (robot-at ?r ?to))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (+ 2 (* 3 (energy-rate ?r)))))))

  (:durative-action traverse-shared-corridor
    :parameters (?r - robot ?from - location ?to - location ?corridor - resource)
    :duration (= ?duration (+ 4 (/ 3 (speed ?r))))
    :condition (and
      (at start (robot-at ?r ?from))
      (at start (connected ?from ?to))
      (at start (can-move ?r ?from ?to))
      (at start (corridor-link ?from ?to))
      (at start (uses-corridor ?from ?to ?corridor))
      (at start (available ?corridor))
      (at start (can-enter ?r ?to))
      (at start (robot-free ?r))
      (at start (robot-has ?r nav-cap))
      (at start (>= (battery ?r) (* 4 (energy-rate ?r))))
      (over all (not (blocked ?from ?to))))
    :effect (and
      (at start (not (available ?corridor)))
      (at start (not (robot-free ?r)))
      (at start (not (robot-at ?r ?from)))
      (at start (decrease (battery ?r) (* 4 (energy-rate ?r))))
      (at end (robot-at ?r ?to))
      (at end (available ?corridor))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (+ 5 (* 4 (energy-rate ?r)))))))

  (:durative-action charge-robot
    :parameters (?r - robot ?l - location ?dock - resource)
    :duration (= ?duration 10)
    :condition (and
      (over all (robot-at ?r ?l))
      (at start (charger-for ?dock ?l))
      (at start (available ?dock))
      (at start (robot-free ?r)))
    :effect (and
      (at start (not (available ?dock)))
      (at start (not (robot-free ?r)))
      (at end (assign (battery ?r) (battery-max ?r)))
      (at end (available ?dock))
      (at end (robot-free ?r))
      (at end (increase (total-cost) 1))))

  (:durative-action pick-item
    :parameters (?r - robot ?i - item ?l - location)
    :duration (= ?duration (+ 1 (item-size ?i)))
    :condition (and
      (over all (robot-at ?r ?l))
      (at start (item-at ?i ?l))
      (at start (robot-free ?r))
      (at start (robot-has ?r delivery-cap))
      (at start (can-pick ?r ?i))
      (at start (<= (+ (current-load ?r) (item-weight ?i)) (payload-capacity ?r))))
    :effect (and
      (at start (not (robot-free ?r)))
      (at start (not (item-at ?i ?l)))
      (at end (carrying ?r ?i))
      (at end (increase (current-load ?r) (item-weight ?i)))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (item-size ?i)))))

  (:durative-action deliver-item
    :parameters (?r - robot ?i - item ?p - person ?l - location ?q - request)
    :duration (= ?duration (+ 2 (task-duration ?q)))
    :condition (and
      (over all (robot-at ?r ?l))
      (over all (person-at ?p ?l))
      (at start (carrying ?r ?i))
      (at start (robot-free ?r))
      (at start (robot-has ?r delivery-cap))
      (at start (can-deliver ?r ?q))
      (at start (request-person ?q ?p))
      (at start (request-item ?q ?i))
      (at start (request-destination ?q ?l))
      (at start (request-capability ?q delivery-cap)))
    :effect (and
      (at start (not (robot-free ?r)))
      (at start (not (carrying ?r ?i)))
      (at end (delivered ?i ?p))
      (at end (service-completed ?q))
      (at end (decrease (current-load ?r) (item-weight ?i)))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (request-priority ?q)))))

  (:durative-action handover-item
    :parameters (?from - robot ?to - robot ?i - item ?l - location)
    :duration (= ?duration 3)
    :condition (and
      (over all (robot-at ?from ?l))
      (over all (robot-at ?to ?l))
      (at start (carrying ?from ?i))
      (at start (can-handover ?from ?to ?i ?l))
      (at start (robot-free ?from))
      (at start (robot-free ?to))
      (at start (robot-has ?to delivery-cap))
      (at start (<= (+ (current-load ?to) (item-weight ?i)) (payload-capacity ?to))))
    :effect (and
      (at start (not (robot-free ?from)))
      (at start (not (robot-free ?to)))
      (at start (not (carrying ?from ?i)))
      (at end (carrying ?to ?i))
      (at end (handover-done ?i ?from ?to))
      (at end (decrease (current-load ?from) (item-weight ?i)))
      (at end (increase (current-load ?to) (item-weight ?i)))
      (at end (robot-free ?from))
      (at end (robot-free ?to))
      (at end (increase (total-cost) 4))))

  (:durative-action handover-deliver-item
    :parameters (?from - robot ?to - robot ?i - item ?p - person ?l - location ?q - request)
    :duration (= ?duration (+ 4 (task-duration ?q)))
    :condition (and
      (over all (robot-at ?from ?l))
      (over all (robot-at ?to ?l))
      (over all (person-at ?p ?l))
      (at start (carrying ?from ?i))
      (at start (can-handover ?from ?to ?i ?l))
      (at start (can-deliver ?to ?q))
      (at start (robot-free ?from))
      (at start (robot-free ?to))
      (at start (robot-has ?to delivery-cap))
      (at start (request-person ?q ?p))
      (at start (request-item ?q ?i))
      (at start (request-destination ?q ?l))
      (at start (request-capability ?q delivery-cap)))
    :effect (and
      (at start (not (robot-free ?from)))
      (at start (not (robot-free ?to)))
      (at start (not (carrying ?from ?i)))
      (at end (handover-done ?i ?from ?to))
      (at end (delivered ?i ?p))
      (at end (service-completed ?q))
      (at end (decrease (current-load ?from) (item-weight ?i)))
      (at end (robot-free ?from))
      (at end (robot-free ?to))
      (at end (increase (total-cost) (+ 4 (request-priority ?q))))))

  (:durative-action cooperative-pick-heavy
    :parameters (?left - robot ?right - robot ?i - item ?l - location)
    :duration (= ?duration (+ 4 (item-size ?i)))
    :condition (and
      (over all (robot-at ?left ?l))
      (over all (robot-at ?right ?l))
      (at start (item-at ?i ?l))
      (at start (can-cooperate ?left ?right ?i))
      (at start (robot-free ?left))
      (at start (robot-free ?right))
      (at start (robot-has ?left lift-left-cap))
      (at start (robot-has ?right lift-right-cap)))
    :effect (and
      (at start (not (robot-free ?left)))
      (at start (not (robot-free ?right)))
      (at start (not (item-at ?i ?l)))
      (at end (co-carrying ?left ?right ?i))
      (at end (robot-free ?left))
      (at end (robot-free ?right))
      (at end (increase (total-cost) (+ 8 (item-size ?i))))))

  (:durative-action cooperative-transport-heavy
    :parameters (?left - robot ?right - robot ?i - item ?p - person ?from - location ?to - location ?q - request)
    :duration (= ?duration (+ 9 (task-duration ?q)))
    :condition (and
      (at start (robot-at ?left ?from))
      (at start (robot-at ?right ?from))
      (at start (item-at ?i ?from))
      (over all (person-at ?p ?to))
      (at start (connected ?from ?to))
      (at start (can-move ?left ?from ?to))
      (at start (can-move ?right ?from ?to))
      (at start (can-cooperate ?left ?right ?i))
      (at start (robot-free ?left))
      (at start (robot-free ?right))
      (at start (robot-has ?left lift-left-cap))
      (at start (robot-has ?right lift-right-cap))
      (at start (>= (battery ?left) (* 5 (energy-rate ?left))))
      (at start (>= (battery ?right) (* 5 (energy-rate ?right))))
      (at start (request-person ?q ?p))
      (at start (request-item ?q ?i))
      (at start (request-origin ?q ?from))
      (at start (request-destination ?q ?to))
      (at start (request-capability ?q lift-left-cap)))
    :effect (and
      (at start (not (robot-free ?left)))
      (at start (not (robot-free ?right)))
      (at start (not (robot-at ?left ?from)))
      (at start (not (robot-at ?right ?from)))
      (at start (not (item-at ?i ?from)))
      (at start (decrease (battery ?left) (* 5 (energy-rate ?left))))
      (at start (decrease (battery ?right) (* 5 (energy-rate ?right))))
      (at end (robot-at ?left ?to))
      (at end (robot-at ?right ?to))
      (at end (delivered ?i ?p))
      (at end (service-completed ?q))
      (at end (robot-free ?left))
      (at end (robot-free ?right))
      (at end (increase (total-cost) (+ 12 (request-priority ?q))))))

  (:durative-action cooperative-carry-heavy
    :parameters (?left - robot ?right - robot ?i - item ?from - location ?to - location)
    :duration (= ?duration (+ 5 (/ 3 (speed ?left))))
    :condition (and
      (at start (co-carrying ?left ?right ?i))
      (at start (robot-at ?left ?from))
      (at start (robot-at ?right ?from))
      (at start (connected ?from ?to))
      (at start (can-move ?left ?from ?to))
      (at start (can-move ?right ?from ?to))
      (at start (not (blocked ?from ?to)))
      (at start (can-enter ?left ?to))
      (at start (can-enter ?right ?to))
      (at start (robot-free ?left))
      (at start (robot-free ?right))
      (at start (>= (battery ?left) (* 5 (energy-rate ?left))))
      (at start (>= (battery ?right) (* 5 (energy-rate ?right))))
      (over all (not (blocked ?from ?to))))
    :effect (and
      (at start (not (robot-free ?left)))
      (at start (not (robot-free ?right)))
      (at start (not (robot-at ?left ?from)))
      (at start (not (robot-at ?right ?from)))
      (at start (decrease (battery ?left) (* 5 (energy-rate ?left))))
      (at start (decrease (battery ?right) (* 5 (energy-rate ?right))))
      (at end (robot-at ?left ?to))
      (at end (robot-at ?right ?to))
      (at end (robot-free ?left))
      (at end (robot-free ?right))
      (at end (increase (total-cost) 10))))

  (:durative-action cooperative-deliver-heavy
    :parameters (?left - robot ?right - robot ?i - item ?p - person ?l - location ?q - request)
    :duration (= ?duration (+ 5 (task-duration ?q)))
    :condition (and
      (over all (robot-at ?left ?l))
      (over all (robot-at ?right ?l))
      (over all (person-at ?p ?l))
      (at start (co-carrying ?left ?right ?i))
      (at start (robot-free ?left))
      (at start (robot-free ?right))
      (at start (request-person ?q ?p))
      (at start (request-item ?q ?i))
      (at start (request-destination ?q ?l))
      (at start (request-capability ?q lift-left-cap)))
    :effect (and
      (at start (not (robot-free ?left)))
      (at start (not (robot-free ?right)))
      (at start (not (co-carrying ?left ?right ?i)))
      (at end (delivered ?i ?p))
      (at end (service-completed ?q))
      (at end (robot-free ?left))
      (at end (robot-free ?right))
      (at end (increase (total-cost) (request-priority ?q)))))

  (:durative-action check-in-visitor
    :parameters (?r - robot ?p - person ?l - location ?q - request ?terminal - resource)
    :duration (= ?duration (+ 2 (task-duration ?q)))
    :condition (and
      (over all (robot-at ?r ?l))
      (over all (person-at ?p ?l))
      (at start (available ?terminal))
      (at start (uses-terminal ?q ?terminal))
      (at start (robot-free ?r))
      (at start (robot-has ?r admin-cap))
      (at start (request-person ?q ?p))
      (at start (request-origin ?q ?l))
      (at start (request-destination ?q ?l))
      (at start (request-capability ?q admin-cap)))
    :effect (and
      (at start (not (available ?terminal)))
      (at start (not (robot-free ?r)))
      (at end (checked-in ?p))
      (at end (service-completed ?q))
      (at end (available ?terminal))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (request-priority ?q)))))

  (:durative-action guide-person
    :parameters (?r - robot ?p - person ?from - location ?to - location ?q - request)
    :duration (= ?duration (+ 3 (/ 3 (speed ?r))))
    :condition (and
      (at start (robot-at ?r ?from))
      (at start (person-at ?p ?from))
      (at start (connected ?from ?to))
      (at start (can-move ?r ?from ?to))
      (at start (not (blocked ?from ?to)))
      (at start (can-enter ?r ?to))
      (at start (robot-free ?r))
      (at start (robot-has ?r guide-cap))
      (at start (can-guide ?r ?q))
      (at start (request-person ?q ?p))
      (at start (request-origin ?q ?from))
      (at start (request-destination ?q ?to))
      (at start (request-capability ?q guide-cap))
      (at start (>= (battery ?r) (* 3 (energy-rate ?r))))
      (over all (not (blocked ?from ?to))))
    :effect (and
      (at start (not (robot-free ?r)))
      (at start (not (robot-at ?r ?from)))
      (at start (not (person-at ?p ?from)))
      (at start (decrease (battery ?r) (* 3 (energy-rate ?r))))
      (at end (robot-at ?r ?to))
      (at end (person-at ?p ?to))
      (at end (guided ?p ?to))
      (at end (service-completed ?q))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (request-priority ?q)))))

  (:durative-action comfort-person
    :parameters (?r - robot ?p - person ?l - location ?q - request)
    :duration (= ?duration (+ 3 (task-duration ?q)))
    :condition (and
      (over all (robot-at ?r ?l))
      (over all (person-at ?p ?l))
      (at start (robot-free ?r))
      (at start (robot-has ?r social-cap))
      (at start (can-comfort ?r ?q))
      (at start (request-person ?q ?p))
      (at start (request-origin ?q ?l))
      (at start (request-destination ?q ?l))
      (at start (request-capability ?q social-cap)))
    :effect (and
      (at start (not (robot-free ?r)))
      (at end (comforted ?p))
      (at end (service-completed ?q))
      (at end (robot-free ?r))
      (at end (increase (total-cost) (request-priority ?q)))))

  (:durative-action remote-assist
    :parameters (?monitor - robot ?actor - robot ?p - person ?station - location ?l - location ?q - request ?terminal - resource)
    :duration (= ?duration (+ 4 (task-duration ?q)))
    :condition (and
      (over all (robot-at ?monitor ?station))
      (over all (robot-at ?actor ?l))
      (over all (person-at ?p ?l))
      (at start (available ?terminal))
      (at start (uses-terminal ?q ?terminal))
      (at start (robot-free ?monitor))
      (at start (robot-free ?actor))
      (at start (robot-has ?monitor monitor-cap))
      (at start (robot-has ?actor social-cap))
      (at start (can-assist ?monitor ?actor ?q))
      (at start (request-person ?q ?p))
      (at start (request-origin ?q ?station))
      (at start (request-destination ?q ?l))
      (at start (request-capability ?q monitor-cap))
      (at start (>= (battery ?monitor) 4)))
    :effect (and
      (at start (not (available ?terminal)))
      (at start (not (robot-free ?monitor)))
      (at start (not (robot-free ?actor)))
      (at start (decrease (battery ?monitor) 4))
      (at end (assisted ?p))
      (at end (service-completed ?q))
      (at end (available ?terminal))
      (at end (robot-free ?monitor))
      (at end (robot-free ?actor))
      (at end (increase (total-cost) (request-priority ?q)))))
)
